# numpy 

In [10]:
import numpy as np

In [11]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
a[1]

2

In [13]:
import time
import sys

In [14]:
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [15]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [16]:
size=100000

In [17]:
L1= range(size)
L2= range(size)
A1=np.arange(size)
A2=np.arange(size)

In [18]:
start= time.time()
result= [(x+y) for x,y in zip(L1,L2)]

print("python list took:",(time.time()-start)*1000)

python list took: 19.97852325439453


In [19]:
start=time.time()
result=A1+A2
print("numpy array took:",(time.time()-start)*1000)

numpy array took: 2.949953079223633


In [20]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a.ndim

2

In [23]:
a.itemsize

4

In [24]:
a.shape

(3, 2)

In [26]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
a.itemsize

8

In [28]:
a.shape

(3, 2)

In [30]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
l=range(5)
l

range(0, 5)

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
print('concatenation example:')
print(np.char.add(['hello','hi'],['abc','xyz']))

concatenation example:
['helloabc' 'hixyz']


In [41]:
print(np.char.center('hello',20,fillchar='-'))

-------hello--------


In [42]:
print(np.char.capitalize('hello world'))

Hello world


In [44]:
print(np.char.title('how are you doing?'))

How Are You Doing?


In [47]:
print(np.char.lower('hello in my world!'))
print(np.char.lower('WORLD'))

hello in my world!
world


In [48]:
print(np.char.upper(['python','dataframe']))
print(np.char.lower('PYTHON IS NOT SO EASY'))

['PYTHON' 'DATAFRAME']
python is not so easy


In [49]:
print(np.char.split('did you come to my home yesterday?'))

['did', 'you', 'come', 'to', 'my', 'home', 'yesterday?']


In [52]:
print(np.char.splitlines('Hey\n will you come tomorrow?'))

['Hey', ' will you come tomorrow?']


In [56]:
print(np.char.strip(['ninai','hinai','minai'],'i'))

['nina' 'hina' 'mina']


In [58]:
print(np.char.join([':','-'],['none','hour']))

['n:o:n:e' 'h-o-u-r']


In [60]:
print(np.char.replace('He is good in sports.','is','will be'))

He will be good in sports.
