In [104]:
import numpy as np

In [2]:
python_list = [3,4,8,9,10]

In [3]:
python_list

[3, 4, 8, 9, 10]

In [10]:
python_array=np.array(python_list)

In [11]:
len(python_array.shape)

1

In [12]:
python_array.shape

(5,)

In [13]:
python_list_list= [[1,5,7], [10,8,6]]

In [14]:
python_list_list

[[1, 5, 7], [10, 8, 6]]

In [15]:
python_array1 = np.array(python_list_list)

In [16]:
python_array1.shape

(2, 3)

In [17]:
len(python_array1)

2

In [18]:
python_array1

array([[ 1,  5,  7],
       [10,  8,  6]])

In [19]:
list(range(5))

[0, 1, 2, 3, 4]

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.random

<module 'numpy.random' from 'C:\\Users\\hp\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [26]:
np.random.randint(5)

1

In [30]:
np.random.randint(5, size=(2,2))

array([[4, 1],
       [3, 4]])

In [31]:
arr= np.random.rand(5,5)

In [32]:
arr

array([[0.01789034, 0.8450996 , 0.8454875 , 0.82064559, 0.75190797],
       [0.02722988, 0.29804526, 0.01936764, 0.8293007 , 0.66587012],
       [0.71117188, 0.17196384, 0.00686814, 0.02611708, 0.46409984],
       [0.27249713, 0.93289517, 0.48097813, 0.70050954, 0.61873767],
       [0.77873528, 0.1438765 , 0.97120145, 0.52620383, 0.32339355]])

In [33]:
arr.shape

(5, 5)

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr[:4]

array([[0.01789034, 0.8450996 , 0.8454875 , 0.82064559, 0.75190797],
       [0.02722988, 0.29804526, 0.01936764, 0.8293007 , 0.66587012],
       [0.71117188, 0.17196384, 0.00686814, 0.02611708, 0.46409984],
       [0.27249713, 0.93289517, 0.48097813, 0.70050954, 0.61873767]])

In [36]:
arr[4:]

array([[0.77873528, 0.1438765 , 0.97120145, 0.52620383, 0.32339355]])

In [37]:
arr[2:5]

array([[0.71117188, 0.17196384, 0.00686814, 0.02611708, 0.46409984],
       [0.27249713, 0.93289517, 0.48097813, 0.70050954, 0.61873767],
       [0.77873528, 0.1438765 , 0.97120145, 0.52620383, 0.32339355]])

In [38]:
arr[:, :4]

array([[0.01789034, 0.8450996 , 0.8454875 , 0.82064559],
       [0.02722988, 0.29804526, 0.01936764, 0.8293007 ],
       [0.71117188, 0.17196384, 0.00686814, 0.02611708],
       [0.27249713, 0.93289517, 0.48097813, 0.70050954],
       [0.77873528, 0.1438765 , 0.97120145, 0.52620383]])

In [39]:
arr[1,1]

0.2980452582864882

In [40]:
arr[:-2]

array([[0.01789034, 0.8450996 , 0.8454875 , 0.82064559, 0.75190797],
       [0.02722988, 0.29804526, 0.01936764, 0.8293007 , 0.66587012],
       [0.71117188, 0.17196384, 0.00686814, 0.02611708, 0.46409984]])

In [46]:
int_arr = np.random.randint(5,size=(6,8))

In [47]:
int_arr

array([[1, 4, 0, 2, 0, 1, 2, 3],
       [2, 2, 0, 4, 1, 0, 0, 2],
       [4, 4, 2, 2, 1, 0, 4, 1],
       [1, 3, 1, 2, 1, 2, 0, 4],
       [3, 4, 0, 4, 4, 4, 3, 3],
       [2, 1, 3, 2, 1, 0, 3, 1]])

In [48]:
int_arr_0 = int_arr[0]

In [49]:
int_arr_0

array([1, 4, 0, 2, 0, 1, 2, 3])

In [50]:
int_arr_0 == 0

array([False, False,  True, False,  True, False, False, False])

In [51]:
int_arr_0 == 1

array([ True, False, False, False, False,  True, False, False])

In [52]:
int_arr_0 == 2

array([False, False, False,  True, False, False,  True, False])

In [60]:
marks = [[4,6,8],[1,3,7],[0,8,5]]

In [61]:
marks[0]

[4, 6, 8]

In [62]:
marks[0][0], marks[1][0], marks[2][0]

(4, 1, 0)

In [63]:
marks_transpose = []
for i in range(len(marks[0])):
    marks_transpose.append([])
    for j in range(len(marks)):
        marks_transpose[i].append(marks[j][i])

In [64]:
marks_transpose

[[4, 1, 0], [6, 3, 8], [8, 7, 5]]

In [65]:
marks_arr = np.array(marks)

In [66]:
marks_arr

array([[4, 6, 8],
       [1, 3, 7],
       [0, 8, 5]])

In [67]:
marks_arr.T

array([[4, 1, 0],
       [6, 3, 8],
       [8, 7, 5]])

In [68]:
marks_arr.sum(0)

array([ 5, 17, 20])

In [69]:
marks_arr

array([[4, 6, 8],
       [1, 3, 7],
       [0, 8, 5]])

In [74]:
grace_marks = np.array([[1,2,3]])

In [77]:
grace_marks.T

array([[1],
       [2],
       [3]])

In [76]:
marks_arr+grace_marks

array([[ 5,  8, 11],
       [ 2,  5, 10],
       [ 1, 10,  8]])

In [92]:
marks

[[4, 6, 8], [1, 3, 7], [0, 8, 5]]

In [108]:
weight_list =[[0.4], [0.2], [0.32]]

In [109]:
results=[]
for i in range(len(marks)):
    for j in range(len(weight_list)):
        curr_sum=0
    for k in range(len(marks[i])):
        curr_sum += marks[i][k]* weight_list[j][k]
    results.append(curr_sum)

IndexError: list index out of range

In [110]:
results

[]

In [111]:
weight_arr = np.array(weight_list)

In [112]:
weight_arr.shape

(3, 1)

In [114]:
a=marks_arr @ weight_arr

In [119]:
a.shape

(3, 1)